# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeliveryDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setTable(self, id):
        self.parent.c.execute("SELECT order_id, delivered_by, (SELECT CONCAT(first_name, ' ' , last_name) from user where id = received_by), DATE_FORMAT(timestamp, '%b %d, %Y %I:%i:%S %p') as timestamp from delivery where id = %s", (id, ))
        result = self.parent.c.fetchone()
        for i, col in enumerate(result):
            col = "Anonymous" if col is None else col
            item = QtWidgets.QTableWidgetItem(str(col))
            item.setFlags(item.flags() | QtCore.Qt.ItemIsEditable| QtCore.Qt.ItemIsSelectable)
            align = QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter
            item.setTextAlignment(align)
            self.tableWidget.setItem(0, i, item)
        self.parent.c.execute("SELECT (SELECT barcode from product where id = product_id), (select name from product where id = product_id), expected, delivered from delivery_product where delivery_id = %s", (id,))
        deliveries =  self.parent.c.fetchall()

        self.tableWidget_2.setRowCount(len(deliveries))
        for i, delivery in enumerate(deliveries):
            for j, col in enumerate(delivery):
                item = QtWidgets.QTableWidgetItem(str(col))
                if j > 1:
                    align = QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter
                else:
                    align = QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter
                item.setTextAlignment(align)
                self.tableWidget_2.setItem(i, j, item)


    def setupUi(self, Form, parent):
        self.parent = parent
        Form.setObjectName("Form")
        Form.resize(600, 437)
        Form.setStyleSheet("QWidget#Form {background-color:White;}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        
        self.tableWidget.verticalHeader().hide()
        self.tableWidget.setColumnWidth(0, 120)
        self.tableWidget.setColumnWidth(1, 130)
        self.tableWidget.setColumnWidth(2, 130)
        self.tableWidget.setColumnWidth(3, 195)
        self.tableWidget.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tableWidget.setSelectionMode(QtWidgets.QTableView.SingleSelection)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(Form)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 100, 581, 321))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_2.verticalHeader().hide()
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        
        header = self.tableWidget_2.horizontalHeader()
        self.tableWidget_2.verticalHeader().hide()
        self.tableWidget_2.setColumnWidth(0, 110)
        self.tableWidget_2.setColumnWidth(1, 280)
        self.tableWidget_2.setColumnWidth(2, 90)
        self.tableWidget_2.setColumnWidth(3, 90)
        
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tableWidget_2.setSelectionMode(QtWidgets.QTableView.SingleSelection)
        self.tableWidget_2.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Fixed)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Fixed)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.Fixed)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.Fixed)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Delivery Detail"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Order ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Delivered By"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Received By"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Date & Time"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Barcode"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Product"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Expected"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Received"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
