# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeliveryRecords.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import DeliveryDetails

class Ui_Form(object):
    def showDetails(self):
        row = self.tableWidget.currentRow()
        order_id = self.tableWidget.item(row, 0).text()
        self.parent.c.execute("SELECT id from delivery where order_id = %s", (order_id, ))
        _id = self.parent.c.fetchone()[0]
        self.DeliveryDetails_ui.setTable(_id)
        self.DeliveryDetailsWidget.show()

    def setTable(self):
        self.tableWidget.setRowCount(len(self.deliveries))
        
        for i, delivery in enumerate(self.deliveries):
            for j, item in enumerate(delivery):
                item = "Anynonmous" if not item else item
                item = QtWidgets.QTableWidgetItem(str(item))
                self.tableWidget.setItem(i, j, item)


    def setupUi(self, Form, parent):
        self.parent = parent
        
        self.DeliveryDetailsWidget = QtWidgets.QWidget()
        self.DeliveryDetails_ui = DeliveryDetails.Ui_Form()
        self.DeliveryDetails_ui.setupUi(self.DeliveryDetailsWidget, self.parent)
        self.DeliveryDetailsWidget.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.setObjectName("Form")
        Form.resize(600, 350)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 541, 261))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.verticalHeader().hide()
        self.tableWidget.setColumnWidth(0, 118)
        self.tableWidget.setColumnWidth(1, 120)
        self.tableWidget.setColumnWidth(2, 118)
        self.tableWidget.setColumnWidth(3, 165)
        self.tableWidget.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tableWidget.setSelectionMode(QtWidgets.QTableView.SingleSelection)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.doubleClicked.connect(self.showDetails)
        
        header = self.tableWidget.horizontalHeader()
        
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Fixed)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Fixed)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.Fixed)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.Fixed)

        self.parent.c.execute("SELECT order_id, delivered_by, (SELECT CONCAT(first_name, ' ' , last_name) from user where id = received_by), DATE_FORMAT(timestamp, '%b %d, %Y %I:%i:%S %p') as timestamp from delivery")
        self.deliveries = self.parent.c.fetchall()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Delivery Record"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Order ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Delivered By"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Received By"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Timestamp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)

    Form.show()
    sys.exit(app.exec_())
