# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InquireWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import InquireResult

class Ui_Dialog(object):
    def showResult(self):
        barcode = self.lineEdit.text()
        self.cursor.execute("SELECT name, price, stock FROM product WHERE barcode = %s", (barcode, ))
        result = self.cursor.fetchone()
        if result:
            self.InquireResult_ui.inquireName.setText(result[0])
            self.InquireResult_ui.inquirePrice.setText("{:,.2f}".format(result[1]))
            self.InquireResult_ui.inquireStock.setText(f"Remaining Stock: {result[2]}")
            self.Dialog.hide()
            self.InquireResultDialog.show()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setWindowTitle("Barcode not found")
            msg.setText("No product is registered with this barcode")
            msg.exec_()
            del msg


    def setupUi(self, Dialog, cursor):
        self.cursor = cursor
        self.Dialog = Dialog
        self.Dialog.setObjectName("Dialog")
        self.Dialog.resize(343, 138)
        self.Dialog.setWindowTitle("Dialog")
        self.InquireResultDialog = QtWidgets.QDialog()
        self.InquireResultDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        self.InquireResult_ui = InquireResult.Ui_Dialog()
        self.InquireResult_ui.setupUi(self.InquireResultDialog)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("padding-left: 5px;")
        self.lineEdit.setObjectName("lineEdit")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.splitter)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(self.Dialog)
        self.buttonBox.accepted.connect(self.showResult) # type: ignore
        self.buttonBox.rejected.connect(self.Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self.Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Dialog", "Product Barcode"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Barcode Here"))
