# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReturnProduct.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

ARROW_UP = 16777235
ARROW_DOWN = 16777237
NUMPAD_PLUS = 43
NUMPAD_MINUS = 45

class Ui_Form(object):

    def saveReturn(self):
        count = self.tableWidget.rowCount()
        updated = False
        for i, item in enumerate(self.items):
            _id, returned_orig, product, price, discount, quantity = item
            returned = self.tableWidget.item(i, 4).text()
            returned = int(returned)
            if returned_orig != returned:
                updated = True
                self.parent.c.execute("UPDATE sale SET returned = %s WHERE id = %s", (returned, _id, ))
        self.parent.conn.commit()
        if updated:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setWindowTitle("Returned Items Updated")
            msg.setText("You've updated the returned items")
            msg.exec_()
            del msg
        self.Form.hide()
        self.transactionIdEntry.setText('')

    def moveUp(self):
        currentRow = self.tableWidget.currentRow()
        if self.tableWidget.currentRow() < 0:
            self.tableWidget.setCurrentCell(self.tableWidget.rowCount() - 1, 4)
        else:
            self.tableWidget.setCurrentCell(self.tableWidget.currentRow() - 1, 4)

    
    def moveDown(self):
        row = self.tableWidget.currentRow()
        self.tableWidget.setCurrentCell(row + 1, 4)
        
    def checkKeyPress(self, eve):
        key = eve.key()
        if key == NUMPAD_PLUS:
            self.increaseReturn()
        elif key == NUMPAD_MINUS:
            self.decreaseReturn()
        elif key == ARROW_UP:
            self.moveUp()
        elif key == ARROW_DOWN:
            self.moveDown()

    def increaseReturn(self):
        currRow = self.tableWidget.currentRow()
        currQty = self.tableWidget.item(currRow, 4).text()
        qty = self.tableWidget.item(currRow, 3).text()
        qty = int(qty)
        if int(currQty) < qty:
            currQty = int(currQty) + 1
            item = QtWidgets.QTableWidgetItem(str(currQty))
            item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
            self.tableWidget.setItem(currRow, 4, item)

    def decreaseReturn(self):
        currRow = self.tableWidget.currentRow()
        currQty = self.tableWidget.item(currRow, 4).text()
        if int(currQty) > 0:
            currQty = int(currQty) - 1
            item = QtWidgets.QTableWidgetItem(str(currQty))
            item.setTextAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
            self.tableWidget.setItem(currRow, 4, item)
    
    def isInt(self, val):
        try:
            int(val)
            return True
        except ValueError:
            return False
    def checkTransaction(self):
        transaction_id = self.transactionIdEntry.text()
        if not self.isInt(transaction_id):
            self.transactionIdEntry.setText(transaction_id[:-1])
            if self.transactionIdEntry.text() == "":
                self.tableWidget.setRowCount(0)
        else:
            transaction_id = int(transaction_id)
            self.parent.c.execute("SELECT id, returned, (SELECT name from product where id = product_id), price, discount, quantity FROM sale where transaction_id = %s", (transaction_id, ))
            results = self.parent.c.fetchall()
            self.items = results
            self.tableWidget.setRowCount(len(results))
            for i, result in enumerate(results):
                for j, col in enumerate(result[2:]):
                    if j > 1:
                        align = QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter
                    else:
                        align = QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter     
                    if j == 1 or j == 2:
                        col = "{:,.2f}".format(col)
                    item = QtWidgets.QTableWidgetItem(str(col))
                    item.setTextAlignment(align)
                    self.tableWidget.setItem(i, j, item)
                item = QtWidgets.QTableWidgetItem(str(result[1]))
                align = QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter
                item.setTextAlignment(align)
                self.tableWidget.setItem(i, 4, item)


    def setupUi(self, Form, parent):
        self.parent = parent
        self.Form = Form
        Form.setObjectName("Form")
        Form.setFixedSize(700, 370)
        self.items = []
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 60, 620, 250))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().hide()
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.setColumnWidth(0, 300)
        self.tableWidget.setColumnWidth(1, 90)
        self.tableWidget.setColumnWidth(2, 90)
        self.tableWidget.setColumnWidth(3, 60)
        self.tableWidget.setColumnWidth(4, 60)
        self.tableWidget.setSelectionBehavior(QtWidgets.QTableView.SelectRows)
        self.tableWidget.setSelectionMode(QtWidgets.QTableView.SingleSelection)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.keyPressEvent = self.checkKeyPress
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(300, 320, 111, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton { background-color: #DC3545; color:white; border-radius: 5px;} QPushButton:hover {background-color: #B02A37;}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.saveReturn)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 621, 44))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.transactionIdEntry = QtWidgets.QLineEdit(self.layoutWidget)
        self.transactionIdEntry.textChanged.connect(self.checkTransaction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transactionIdEntry.sizePolicy().hasHeightForWidth())
        self.transactionIdEntry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.transactionIdEntry.setFont(font)
        self.transactionIdEntry.setText("")
        self.transactionIdEntry.setObjectName("transactionIdEntry")
        self.horizontalLayout.addWidget(self.transactionIdEntry)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)

        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 1px solid black; padding: 2px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Product"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Price"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Discount"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Return"))
        self.pushButton.setText(_translate("Form", "Return Items"))
        self.label.setText(_translate("Form", "Transaction ID: "))
        self.label_2.setText(_translate("Form", "Date & Time:"))
        self.label_3.setText(_translate("Form", "November 20, 1994\n"
"5:00PM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
