# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(100, 180, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(100, 100))
        self.toolButton.setMaximumSize(QtCore.QSize(100, 100))
        self.toolButton.setBaseSize(QtCore.QSize(100, 100))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setAutoFillBackground(False)
        self.toolButton.setStyleSheet("border-image: url(:/Images/Images/Hold_Sale.png) 0 0 0 0 stretch stretch")
        self.toolButton.enterEvent = lambda x: self.toolButton.setStyleSheet("border-image: url(:/Images/Images/Hold_Sale_Hovered.png) 0 0 0 0 stretch stretch")
        self.toolButton.leaveEvent = lambda x: self.toolButton.setStyleSheet("border-image: url(:/Images/Images/Hold_Sale.png) 0 0 0 0 stretch stretch")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Form)
        self.toolButton_2.setGeometry(QtCore.QRect(140, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_2.setStyleSheet("background-color: #2db5ff; border-radius: 5px; color: white; border: 1px solid black;")
        self.toolButton_2.enterEvent = lambda x: self.toolButton_2.setStyleSheet("background-color: #2597e4; border-radius: 5px; color: white; border: 1px solid black;")
        self.toolButton_2.leaveEvent = lambda x: self.toolButton_2.setStyleSheet("background-color: #2db5ff; border-radius: 5px; color: white; border: 1px solid black;")
        self.toolButton_2.setObjectName("toolButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.toolButton_2.setText(_translate("Form", "Ok"))
        
import qr_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
